[workspace]
members = [
    "src/clients/c2c_permission",
    "src/libraries/guards",
    "src/libraries/shared_types",
    "src/services/organization",
    "src/services/permission",
    "src/services/storage",
]
resolver = "2"
